### ISSUE TITLE
How should I apply this functionality in dapp?

### ISSUE THREAD

**Issue by pupudaye** [rarimo/rarime#2]
If I want to use this to create a private key identity, and then complete automatic transaction signature processing. what should be done

**Comment by ihordiachenko** [comment]
Hi @pupudaye, we appreciate your interest in our snap!

Unfortunately, the automatic transaction signature processing is outside of the scope of this project. You can check out the identity creation part here: https://github.com/rarimo/rarime/blob/028a8d0645919869133a50fe482a8b094ab4f59e/packages/snap/src/index.ts#L81
